service: products-api
frameworkVersion: '2'
provider:
  name: aws
  runtime: java8

  stage: dev
  region: us-west-2
package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: hello
          method: post
